root = "."      # The root directorky of the project 
tmp_dir = "tmp" # The temp directory where air will store its tem files

[build] # build config 
bin = "main"
cmd = "go build -o {{.Output}} {{.Input}}"
exclude = ["tmp/*", "client/*"]
include = ["**/*.go"]
ignore = ["tmp/*"]
